### ISSUE TITLE
issue saving intent in developer console

### ISSUE THREAD

**Issue by jns4u** [api-ai/api-ai-node-js#10]
hi
i am facing trouble in saving intent. Although i created entities properly and after creating parameter values and speech response it says "Some values in parameters are unresolved:$hotelName".
$hotelName is value for corresponding parameter hotelName and entity @$hotelName.

**Comment by sstepashka** [comment]
hi,

Can you make screenshot of fields and error?

**Comment by jns4u** [comment]
thanks for reply,

i got quick fix, issue was due to missing annotations in Users intents and
got them linked to entities.
