### ISSUE TITLE
Context API is not supported by current client version

### ISSUE THREAD

**Issue by ShoukriKattan** [api-ai/api-ai-node-js#11]
Hi There, 

Right now api-ai-node-js client supports Query and User Entities API but does not support Context API. Any reason this is not supported?

Thanks

**Comment by younes200** [comment]
It looks like it can be sent withing the request parameter : https://github.com/api-ai/api-ai-node-js/blob/052d42a46b17078af341fefefefd8b4cf9752a16/module/query_request.js#L30

**Comment by ShoukriKattan** [comment]
The element you mentioned sets the context as a JSON body parameter on requests such as Query request.  My question was regarding Context endpoint (https://docs.api.ai/docs/contexts)  which can be called separately to set context on a session. 

If I am to follow the conventions of the SDK there needs to be a new call type on the apiai client  such as one can do : 
let apiaiContextRequest = apiAiService.contextRequest  and there needs to be a new type of request
context_request.js which inherits request.js type and points to the /context endpoint and allow to call context endpoint.

**Comment by sstepashka** [comment]
Currently implemented. See https://github.com/api-ai/api-ai-node-js/blob/master/module/contexts_request.js

**Comment by sbcalculas** [comment]
> Currently implemented. See https://github.com/api-ai/api-ai-node-js/blob/master/module/contexts_request.js

I am trying to implement it like this 
-------------------------------------------------------------------------------------------------
global.NLP = require('apiai')(APIAI_TOKEN);
let dialogFlowToken  = "1234567890"
let context = [
        {
            "name": "Sample_Context",
            "parameters": {
                "location": "Bedroom"
            },
            "lifespan": 5
        }
    ];
const apiaiReq = global.NLP.contextsRequest(context, { sessionId: dialogFlowToken });
apiaiReq.on('response', async (response) => {
        console.log(response);
    });
    apiaiReq.on('error', (error) => {
        console.log(error);
    });
    apiaiReq.end();
}
------------------------------------------------------------------------------------------------
The response is 
{"status":{"code":200,"errorType":"success"}}
-----------------------------------------------------------------------------
But in the next request there is no context i am getting back.
