### ISSUE TITLE
Wisdom not working on node

### ISSUE THREAD

**Issue by qadirsuh** [api-ai/api-ai-node-js#15]
Wisdom is working on api-ai dashboard. see below image
http://prntscr.com/cnptu0

I have integrated the api-ai in my node app (Free version)
but its not working in there

here is the response I am getting. 

```
{  
   "id":"0d113e16-e69b-417b-9f69-d34dd9f594c9",
   "timestamp":"2016-09-29T10:38:19.87Z",
   "result":{  
      "source":"agent",
      "resolvedQuery":"Who was Albert Einstein?",
      "contexts":[  

      ],
      "metadata":{  
      },
      "fulfillment":{  
         "speech":""
      },
      "score":0
   },
   "status":{  
      "code":200,
      "errorType":"success"
   }
   "sessionId":"00000000-0000-0000-0000-000000000000"
}
```

please guide me on this issue. What I am missing

**Comment by Gugic** [comment]
According to https://api.ai/pricing/ (and the note in upper-right corner of 'wisdom' domain card) that domain is only available on paid plans.

**Comment by qadirsuh** [comment]
OK! thought so.
