### ISSUE TITLE
try/catch around response processing is unhelpful

### ISSUE THREAD

**Issue by richardgroves** [api-ai/api-ai-node-js#17]
Around https://github.com/api-ai/api-ai-node-js/blob/master/module/request.js#L41 there is a try/catch block around the processing of the response from the server, if it fails then the error callback is called.

This has just caused me a bunch of problems in that I had an error in my response handling code which gets silently consumed and then my error callback code runs - I'd consider that the request.on('error', function(error) {}); function should *only* be called when the server has returned an error - its not designed to handle errors in our own response code - we should do that, and with your try/catch eating them they show up in a very odd way.

Would suggest removing that try/catch and letting user supplied code handle it's own errors when dealing with the response.

**Comment by sstepashka** [comment]
Hi,

I think, you right. This is"try/catch" uses only for handle errors of JSON serialization.

**Comment by richardgroves** [comment]
Ok - I see what it was trying to do now. Looks much better. Thanks.
