### ISSUE TITLE
MPORTANT: Please use unique session ID for each client. Otherwise you may experience unstable behaviour

### ISSUE THREAD

**Issue by umashankarpandey** [api-ai/api-ai-node-js#22]
i am receiving warning in api.ai "IMPORTANT: Please use unique session ID for each client. Otherwise you may experience unstable behaviour"

what i need to do?

**Comment by sstepashka** [comment]
Use unique session id for each client =)

You can generate session id and use id. If you use developing site you can just use hash of some unique value of your users.

**Comment by slidenerd** [comment]
you mean like a UUID?

**Comment by sstepashka** [comment]
@slidenerd Yes, but really you can use some hashes from data. For example, md5  of use email.
