### ISSUE TITLE
ServerError - Wrong response status code.

### ISSUE THREAD

**Issue by aekynr** [api-ai/api-ai-node-js#29]
responseBody: '{\n  "id": "fd0d8064-e7f1-49e8-be8f-acf49bd450ae",\n  "timestamp": "2016-11-16T19:44:02.09Z",\n  "status": {\n    "code": 400,\n    "errorType": "bad_request",\n    "errorDetails": "Required \\u0027sessionId\\u0027 parameter is empty."\n  }\n}',

**Comment by Gugic** [comment]
You should send sessionId with each request. According to [protocol description](https://docs.api.ai/docs/query) it is required.

You can see how to do it in https://github.com/api-ai/api-ai-node-js/blob/master/examples/text_request_with_parameters.js

**Comment by aekynr** [comment]
@Gugic Thanks but it was working so far, what changed?

**Comment by artemgoncharuk** [comment]
Session ID is a required parameter as per docs - https://docs.api.ai/docs/query#query-parameters-and-json-fields

We have started enforcing it - https://docs.api.ai/blog/changelog-november-16-2016

**Comment by naveenkn456** [comment]
I am seeing the same issue in my project, can any of you please help me with the solution?
