### ISSUE TITLE
Change "name" in package.json from apaai

### ISSUE THREAD

**Issue by gregk** [api-ai/api-ai-node-js#3]
If you try to run npm install apiai you will get the following:

npm install apiai
npm WARN package.json apiai@1.0.3 license should be a valid SPDX license expression
npm WARN install Refusing to install apiai as a dependency of itself

The name in package.json conflicts with the package "apiai". A simple change to something like "api-ai-node-js" will fix the problem.

**Comment by xVir** [comment]
It seems the problem resolved now
