### ISSUE TITLE
API.AI speech recognition is going to be deprecated soon.

### ISSUE THREAD

**Issue by Sultan91** [api-ai/api-ai-node-js#35]
Is this true 
![screenshot001](https://cloud.githubusercontent.com/assets/16382530/21459339/72edd178-c94e-11e6-8b96-83c0f97ae622.jpg)
when trying to run the fllowing sample a get an error. 
`var fs = require("fs");

// var apiai = require("../module/apiai");
var apiai = require("apiai");

var app = apiai("token", {
    language: 'eng'
});

var request = app.voiceRequest();

request.on('response', function(response) {
    console.log(response);
});

request.on('error', function(error) {
    console.log(error);
});

fs.readFile("1.wav", function(error, buffer) {
    if (error) {
        console.log(error);
    } else {
        request.write(buffer);
    }

    request.end();
});`

**Comment by sstepashka** [comment]
This is expected response. We doesn't support voice recognition anymore.

Our company's main focus is NLU (natural language understanding) and dialog management. We provide a platform for creating conversational interfaces (called agents) for apps, bots, and devices. These interfaces are designed to receive text as input information.

Depending on your app, bot, or device platform, speech recognition might be available natively. For example, if you are building an Action on Google, Google Home supports speech recognition natively.

For some other platforms, speech recognition can be integrated as an additional component. 

API.AI doesn't provide speech recognition services. You can consider using Google Speech API or other 3rd party solution for speech recognition and use API.AI for building a conversational interface.
