### ISSUE TITLE
cors support on the requests

### ISSUE THREAD

**Issue by nitin42** [api-ai/api-ai-node-js#37]
Just completed my app but when it comes to running it on a local server, I am getting an error "Client was not configured properly". But I don't see this error when I use CORS plugin on my chrome. This is the stack trace : 

```
Fetch API cannot load https://api.api.ai/v1/query?v=20150910. Request header field api-request-source is not allowed by Access-Control-Allow-Headers in preflight response.
```

Please help me resolve this. Its all going good for development but when it comes to deploying, I am stuck.

**Comment by sstepashka** [comment]
Is it like your trouble http://stackoverflow.com/questions/32500073/request-header-field-access-control-allow-headers-is-not-allowed-by-itself-in-pr ?

**Comment by sstepashka** [comment]
I think, trouble in your code, can you provide example to reproduce this issue?

**Comment by nitin42** [comment]
This is my code : 

```javascript
const express = require('express');
const morgan = require('morgan');
const path = require('path');
const cors = require('cors');

const app = express();

const options = {
  origin: '*',
  methods: ['POST', 'GET', 'HEAD', 'OPTION'],
  credentials: true,
  preflightContinue: true,
  maxAge: 3600
};

const port = process.env.PORT || 8000;

app.use(morgan('dev'));
app.use(express.static(path.resolve(__dirname, 'build')));
app.options('*', cors(options));

app.get('*', (req, res) => {
  res.sendFile(path.resolve(__dirname, 'build/index.html'));
});

app.listen(port, () => {
  console.log("Server is listening on port 8000");
});
```

Where the 'build' is the production build folder. When I start my server I get this error : 
```
Fetch API cannot load https://api.api.ai/v1/query?v=20150910. Request header field api-request-source is not allowed by Access-Control-Allow-Headers in preflight response.
```
 and when I trace the error, it takes me to your api  ```  request.on('error', (error) => {
    throw new Error('Client not connected properly.');
  });```

This is how I am using the SDK.

```
export let connect_apiai = (term, callback) => {
  const app = apiai(API.ai KEY);

  let request = app.textRequest(term, {
      sessionId: SESSION_ID
  });

  request.on('response', (response) => {
      if (response['result']['fulfillment']['speech'] !== '') {
        callback(response);
      } else {
        callback(response);
      }
  });
  request.on('error', (error) => {
    throw new Error('Client not connected properly.');
  });
  request.end();
}
```

**Comment by Gugic** [comment]
@nitin42 is there any real reason to use server-side SDK with CORS and preflight requests?

**Comment by nitin42** [comment]
Well, there is no real reason to use the CORS with my server configuration. What I'm trying to say is that normally if I use the SDK with a session id and client token, its working perfectly in the console. But when I am trying to configure the SDK with my frontend code I get this error. This error is related with CORS policy so it won't work. But using the CORS plugin I get no errors. 
One more interesting thing, as soon as I start my plugin and make first request to ```https://api.api.ai/v1/query?v=20150910``` it fetches the JSON as expected from API.ai. After this initial request if I turn the plugin off and then carry on again, IT WORKS.

What actually happening is that the my browser is trying to access this resource from your domain (API.ai) and it needs to make a OPTION request to ```https://api.api.ai/v1/query?v=20150910```. And it is only possible (currently) if I use the CORS plugin.

Something is really strange and I tried every fix, but still no solution.

**Comment by Gugic** [comment]
@nitin42 we've configure servers to add 'api-request-source' header support in CORS requests, check please.

**Comment by nitin42** [comment]
Thanks A LOT. Its working now without any plugin or any cors dependencies in my server configuration.

**Comment by arjun-coursera** [comment]
I tried the 'textrequest' in samples folder of this repo and have the exact same issue. I am running a react js front end app on my localbox http://localhost:3000/. 

`Fetch API cannot load https://api.api.ai/v1/query?v=20150910. Request header field api-request-source is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by jckh1234** [comment]
exact same problem as @arjun-coursera , any update?
