### ISSUE TITLE
i need to Develop intelligent chatbot

### ISSUE THREAD

**Issue by VishnuvardhanYerukala** [api-ai/api-ai-node-js#39]
i am planning to develop intelligent chatbot what are the requirements are required to develop chatbot.
1.Front end which language i need to use and back end which one i need to use.
2.any inbuilt temp lets are available?if it is not available please specify if any???
3.which operating System is best to build Chatbots Windows or ubuntu or MacOS.
4.How to start to build chatbot??? Please specify????

**Comment by Gugic** [comment]
This is a repository of node.js SDK, your question is general and is better to be asked on [api.ai forums](https://discuss.api.ai/top/all)
