### ISSUE TITLE
no parameters in response

### ISSUE THREAD

**Issue by dcsan** [api-ai/api-ai-node-js#43]
when I use the node library, the responses don't have any parameters, ie identified entities.

when I use the preview test console, or the copied curl query, the parameters do appear.

Is there some limitation to how the nodeSDK uses the text query? It seems somehow missing a lot of data in the response.

https://discuss.api.ai/t/parameters-dont-come-back-in-response/4815

**Comment by sstepashka** [comment]
Hi @dcsan,

See [this](https://github.com/api-ai/api-ai-node-js/blob/master/examples/text_request_chinese.js#L16) example.

You shall pass language parameter for languages for non-english languages. So, this parameter default using as language of agent, but this is feature available only for console. In API you shall pass it yourself.

**Comment by whispers16** [comment]
@sstepashka could you post the link example again? , it seems it's broken, thanks

**Comment by dcsan** [comment]
yes there's nothing in the pointed directory except one file:
https://github.com/api-ai/apiai-nodejs-client/tree/master/examples

what param should we pass for language?
