### ISSUE TITLE
Application timezone not set?

### ISSUE THREAD

**Issue by anthonylai** [api-ai/api-ai-node-js#5]
The timezone of the application never seemed to be set, and request.js is using it.
Is there a way we can set the timezone for a request?

**Comment by sstepashka** [comment]
Hello,

You can just provide timezone parameter into options of request

https://github.com/api-ai/api-ai-node-js/blob/master/module/query_request.js#L21
https://github.com/api-ai/api-ai-node-js/blob/master/module/apiai.js#L72

Please check documentation before using it https://docs.api.ai/docs/query
