### ISSUE TITLE
Does the text_request_with_entities.js work?

### ISSUE THREAD

**Issue by PavelPolyakov** [api-ai/api-ai-node-js#7]
Hi,

I'm trying to test `apiai`.
Created the test agent with one intent.

Copied my developer access token to the code and launched the script.

Here is my response:
![image](https://cloud.githubusercontent.com/assets/839290/15276191/5835a62e-1ae1-11e6-98f0-29a4f878ffc4.png)

Are we sure that this example is working? 
As I expected - it would create correspondent entities inside my agent.

Regards,

**Comment by sstepashka** [comment]
Hi, but... Why your run exactly "index.js"? This is library file and it does not using for running. All examples contain 'examples' folder: 

```bash
$ ls examples | grep .js
server_example.js
text_request.js
text_request_with_entities.js
user_entities_request.js
voice_request.js
```

**Comment by PavelPolyakov** [comment]
Hi,Yes, it's index.js, however I have just copied the example code there (and installed the apiai using the npm). So it should work, the other - simple text query example works well.Regards,Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail16.05.2016, 01:08, "Dmitriy Kuragin" <notifications@github.com>:Hi, but... Why your run exactly "index.js"? This is library file and it does not using for running. All examples contain 'examples' folder:$ ls examples grep .js

server_example.js

text_request.js

text_request_with_entities.js

user_entities_request.js

voice_request.js—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub￼

**Comment by sstepashka** [comment]
I was update library for logging detail information about server response. Can you try to run your code with last version of library.

**Comment by PavelPolyakov** [comment]
@sstepashka 
This version of the library is corrupted and couldn't be executed, check the file:
`node_modules/apiai/module/request.js:2` , some problem with comments block.

However, when fixed - here is the response from the server:
```
Server response error with status code: 400
{
  "id": "8a94c266-902a-4ecd-a603-d94019a0ce05",
  "timestamp": "2016-05-16T09:32:48.775Z",
  "status": {
    "code": 400,
    "errorType": "bad_request",
    "errorDetails": "userEntity \u0027dwarfs\u0027 doesn\u0027t exist"
  }
}
```

When I've created an entity `dwarfs` on the `api.ai` the request went well, however, no entities were created (I mean the entity created by me was not updated). Is that expected?

**Comment by sstepashka** [comment]
'userEntities' is Entities specific for every end user. For example,

You create intent 'Call to <contact>', you have entity 'contacts', user entities will override this entities for local user contacts. But this just for example. 


For details see documentation https://docs.api.ai/docs/userentities

Thanks. 

Executable error will be fixed in few minutes. Thank you!!!
