### ISSUE TITLE
Unnable to resolve module events of request.js using react-native

### ISSUE THREAD

**Issue by sirgalleto** [api-ai/api-ai-node-js#8]
<img width="361" alt="screen shot 2016-05-21 at 9 30 28 pm" src="https://cloud.githubusercontent.com/assets/5873627/15451804/61cd0c04-1f9b-11e6-9fe3-328561b2d9e6.png">

**Comment by sstepashka** [comment]
Hi,

Where you find information, that current module support react-native?

**Comment by bardu** [comment]
Are there any plans for react-native SDK?

**Comment by superquest** [comment]
I'm also very interested in React Native support.

**Comment by sirgalleto** [comment]
I'm in fucking agreement

**Comment by spoeck** [comment]
I'm wrapping the Android SDK and the iOS SDK for react-native:
https://github.com/innFactory/react-native-api-ai
Android works already now I'm working on iOS.

**Comment by CyrusChew** [comment]
anyone could share more about react-native? in my folder only app.js, as its combine together with iOS & Android.. but in the git its 2 folder that iOS and Android.. what should we do?
